trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'vasualgoVM'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m unittest discover
    displayName: 'Run tests'
